import { stacks, type TechStack } from "@/data/stacks";

export type Answers = {
  project: string;
  scale: string;
  experience: string;
  timeline: string;
  priority: string;
};

type ScoreWeights = Record<string, number>;

// Each answer maps to weighted scores for each stack ID
const scoringMatrix: Record<string, Record<string, ScoreWeights>> = {
  project: {
    saas: {
      "nextjs-supabase": 10,
      "nextjs-prisma": 9,
      "nestjs-postgres": 6,
      "remix-supabase": 7,
      "laravel-vue": 5,
      "django-postgres": 5,
      "python-fastapi": 3,
      "nextjs-ai": 4,
      "react-native-expo": 1,
      "flutter-firebase": 1,
      "nextjs-shopify": 1,
      "spring-boot-k8s": 4,
      "go-grpc": 3,
      "astro-netlify": 0,
    },
    mobile: {
      "react-native-expo": 10,
      "flutter-firebase": 10,
      "nextjs-supabase": 3,
      "nextjs-prisma": 2,
      "nestjs-postgres": 4,
      "python-fastapi": 3,
      "nextjs-ai": 2,
      "django-postgres": 2,
      "laravel-vue": 1,
      "spring-boot-k8s": 3,
      "go-grpc": 2,
      "remix-supabase": 1,
      "nextjs-shopify": 0,
      "astro-netlify": 0,
    },
    ecommerce: {
      "nextjs-shopify": 10,
      "nextjs-supabase": 6,
      "nextjs-prisma": 7,
      "laravel-vue": 8,
      "django-postgres": 5,
      "nestjs-postgres": 4,
      "remix-supabase": 5,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "python-fastapi": 2,
      "nextjs-ai": 1,
      "spring-boot-k8s": 3,
      "go-grpc": 1,
      "astro-netlify": 3,
    },
    data: {
      "python-fastapi": 10,
      "django-postgres": 8,
      "nestjs-postgres": 6,
      "nextjs-prisma": 5,
      "spring-boot-k8s": 7,
      "go-grpc": 6,
      "nextjs-ai": 7,
      "nextjs-supabase": 3,
      "laravel-vue": 2,
      "react-native-expo": 0,
      "flutter-firebase": 0,
      "nextjs-shopify": 0,
      "remix-supabase": 2,
      "astro-netlify": 0,
    },
    ai: {
      "nextjs-ai": 10,
      "python-fastapi": 9,
      "django-postgres": 6,
      "nextjs-prisma": 5,
      "nextjs-supabase": 4,
      "nestjs-postgres": 3,
      "go-grpc": 2,
      "spring-boot-k8s": 3,
      "laravel-vue": 1,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "nextjs-shopify": 0,
      "remix-supabase": 2,
      "astro-netlify": 0,
    },
    internal: {
      "nextjs-supabase": 8,
      "nextjs-prisma": 8,
      "laravel-vue": 7,
      "django-postgres": 9,
      "nestjs-postgres": 6,
      "remix-supabase": 5,
      "python-fastapi": 5,
      "spring-boot-k8s": 4,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "nextjs-ai": 3,
      "go-grpc": 2,
      "nextjs-shopify": 0,
      "astro-netlify": 1,
    },
    api: {
      "nestjs-postgres": 10,
      "python-fastapi": 9,
      "go-grpc": 10,
      "spring-boot-k8s": 8,
      "django-postgres": 7,
      "nextjs-prisma": 5,
      "nextjs-supabase": 3,
      "laravel-vue": 4,
      "nextjs-ai": 3,
      "react-native-expo": 0,
      "flutter-firebase": 0,
      "nextjs-shopify": 0,
      "remix-supabase": 2,
      "astro-netlify": 0,
    },
    marketing: {
      "astro-netlify": 10,
      "nextjs-supabase": 6,
      "nextjs-prisma": 4,
      "remix-supabase": 7,
      "laravel-vue": 4,
      "django-postgres": 2,
      "nextjs-shopify": 3,
      "nestjs-postgres": 0,
      "python-fastapi": 0,
      "nextjs-ai": 1,
      "react-native-expo": 0,
      "flutter-firebase": 0,
      "spring-boot-k8s": 0,
      "go-grpc": 0,
    },
  },
  scale: {
    mvp: {
      "nextjs-supabase": 10,
      "nextjs-prisma": 7,
      "remix-supabase": 8,
      "astro-netlify": 9,
      "laravel-vue": 7,
      "react-native-expo": 8,
      "flutter-firebase": 8,
      "nextjs-ai": 6,
      "python-fastapi": 5,
      "django-postgres": 4,
      "nextjs-shopify": 5,
      "nestjs-postgres": 2,
      "spring-boot-k8s": 0,
      "go-grpc": 2,
    },
    growth: {
      "nextjs-prisma": 9,
      "nextjs-supabase": 7,
      "nestjs-postgres": 7,
      "remix-supabase": 7,
      "django-postgres": 7,
      "laravel-vue": 6,
      "python-fastapi": 7,
      "nextjs-ai": 6,
      "react-native-expo": 6,
      "flutter-firebase": 6,
      "nextjs-shopify": 7,
      "spring-boot-k8s": 5,
      "go-grpc": 6,
      "astro-netlify": 5,
    },
    scale: {
      "nestjs-postgres": 9,
      "go-grpc": 10,
      "spring-boot-k8s": 9,
      "nextjs-prisma": 7,
      "python-fastapi": 7,
      "django-postgres": 6,
      "remix-supabase": 8,
      "nextjs-supabase": 4,
      "nextjs-shopify": 6,
      "laravel-vue": 4,
      "nextjs-ai": 5,
      "react-native-expo": 5,
      "flutter-firebase": 5,
      "astro-netlify": 6,
    },
    enterprise: {
      "spring-boot-k8s": 10,
      "nestjs-postgres": 9,
      "go-grpc": 9,
      "django-postgres": 7,
      "nextjs-prisma": 6,
      "python-fastapi": 6,
      "nextjs-shopify": 5,
      "nextjs-supabase": 2,
      "laravel-vue": 3,
      "remix-supabase": 5,
      "nextjs-ai": 4,
      "react-native-expo": 4,
      "flutter-firebase": 4,
      "astro-netlify": 3,
    },
  },
  experience: {
    javascript: {
      "nextjs-supabase": 10,
      "nextjs-prisma": 10,
      "nestjs-postgres": 9,
      "remix-supabase": 9,
      "nextjs-ai": 8,
      "nextjs-shopify": 8,
      "react-native-expo": 9,
      "astro-netlify": 7,
      "laravel-vue": 4,
      "django-postgres": 1,
      "python-fastapi": 1,
      "flutter-firebase": 2,
      "spring-boot-k8s": 1,
      "go-grpc": 1,
    },
    python: {
      "python-fastapi": 10,
      "django-postgres": 10,
      "nextjs-ai": 7,
      "nextjs-supabase": 3,
      "nextjs-prisma": 3,
      "nestjs-postgres": 2,
      "laravel-vue": 1,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "nextjs-shopify": 2,
      "spring-boot-k8s": 1,
      "go-grpc": 2,
      "remix-supabase": 2,
      "astro-netlify": 3,
    },
    java: {
      "spring-boot-k8s": 10,
      "nestjs-postgres": 5,
      "flutter-firebase": 4,
      "go-grpc": 3,
      "nextjs-supabase": 2,
      "nextjs-prisma": 2,
      "python-fastapi": 1,
      "django-postgres": 1,
      "laravel-vue": 1,
      "react-native-expo": 3,
      "nextjs-ai": 2,
      "nextjs-shopify": 1,
      "remix-supabase": 2,
      "astro-netlify": 2,
    },
    go: {
      "go-grpc": 10,
      "nestjs-postgres": 3,
      "spring-boot-k8s": 3,
      "python-fastapi": 2,
      "nextjs-supabase": 2,
      "nextjs-prisma": 2,
      "django-postgres": 1,
      "laravel-vue": 1,
      "react-native-expo": 1,
      "flutter-firebase": 1,
      "nextjs-ai": 2,
      "nextjs-shopify": 1,
      "remix-supabase": 2,
      "astro-netlify": 2,
    },
    ruby: {
      "nextjs-supabase": 4,
      "nextjs-prisma": 4,
      "django-postgres": 5,
      "laravel-vue": 5,
      "remix-supabase": 4,
      "nestjs-postgres": 3,
      "python-fastapi": 3,
      "astro-netlify": 4,
      "react-native-expo": 3,
      "flutter-firebase": 2,
      "nextjs-ai": 3,
      "nextjs-shopify": 3,
      "spring-boot-k8s": 2,
      "go-grpc": 2,
    },
    dotnet: {
      "spring-boot-k8s": 5,
      "nestjs-postgres": 4,
      "nextjs-prisma": 3,
      "go-grpc": 4,
      "nextjs-supabase": 3,
      "django-postgres": 2,
      "python-fastapi": 2,
      "laravel-vue": 2,
      "react-native-expo": 2,
      "flutter-firebase": 3,
      "nextjs-ai": 2,
      "nextjs-shopify": 2,
      "remix-supabase": 3,
      "astro-netlify": 2,
    },
    php: {
      "laravel-vue": 10,
      "nextjs-supabase": 3,
      "nextjs-prisma": 3,
      "django-postgres": 2,
      "nextjs-shopify": 4,
      "nestjs-postgres": 2,
      "python-fastapi": 1,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "nextjs-ai": 2,
      "spring-boot-k8s": 1,
      "go-grpc": 1,
      "remix-supabase": 2,
      "astro-netlify": 4,
    },
    new: {
      "nextjs-supabase": 9,
      "astro-netlify": 8,
      "flutter-firebase": 6,
      "react-native-expo": 5,
      "nextjs-prisma": 5,
      "laravel-vue": 5,
      "remix-supabase": 5,
      "nextjs-shopify": 4,
      "python-fastapi": 4,
      "django-postgres": 3,
      "nextjs-ai": 3,
      "nestjs-postgres": 2,
      "spring-boot-k8s": 1,
      "go-grpc": 1,
    },
  },
  timeline: {
    asap: {
      "nextjs-supabase": 10,
      "astro-netlify": 9,
      "remix-supabase": 7,
      "react-native-expo": 7,
      "flutter-firebase": 6,
      "laravel-vue": 6,
      "nextjs-prisma": 6,
      "nextjs-shopify": 5,
      "python-fastapi": 5,
      "nextjs-ai": 4,
      "django-postgres": 4,
      "nestjs-postgres": 2,
      "go-grpc": 2,
      "spring-boot-k8s": 1,
    },
    normal: {
      "nextjs-prisma": 8,
      "nextjs-supabase": 7,
      "nestjs-postgres": 7,
      "laravel-vue": 7,
      "remix-supabase": 7,
      "python-fastapi": 7,
      "django-postgres": 7,
      "react-native-expo": 7,
      "flutter-firebase": 7,
      "nextjs-ai": 6,
      "nextjs-shopify": 6,
      "astro-netlify": 6,
      "go-grpc": 5,
      "spring-boot-k8s": 4,
    },
    planned: {
      "nestjs-postgres": 8,
      "spring-boot-k8s": 7,
      "go-grpc": 8,
      "nextjs-prisma": 7,
      "django-postgres": 7,
      "python-fastapi": 7,
      "nextjs-ai": 7,
      "laravel-vue": 6,
      "nextjs-shopify": 6,
      "nextjs-supabase": 5,
      "remix-supabase": 6,
      "react-native-expo": 6,
      "flutter-firebase": 6,
      "astro-netlify": 5,
    },
    "no-rush": {
      "spring-boot-k8s": 9,
      "go-grpc": 9,
      "nestjs-postgres": 8,
      "nextjs-prisma": 7,
      "django-postgres": 7,
      "python-fastapi": 7,
      "nextjs-ai": 7,
      "laravel-vue": 6,
      "nextjs-shopify": 5,
      "nextjs-supabase": 4,
      "remix-supabase": 5,
      "react-native-expo": 5,
      "flutter-firebase": 5,
      "astro-netlify": 4,
    },
  },
  priority: {
    speed: {
      "nextjs-supabase": 10,
      "astro-netlify": 9,
      "remix-supabase": 7,
      "react-native-expo": 7,
      "flutter-firebase": 6,
      "laravel-vue": 7,
      "nextjs-prisma": 6,
      "nextjs-shopify": 5,
      "python-fastapi": 5,
      "nextjs-ai": 4,
      "django-postgres": 4,
      "nestjs-postgres": 2,
      "go-grpc": 2,
      "spring-boot-k8s": 1,
    },
    scalability: {
      "go-grpc": 10,
      "spring-boot-k8s": 9,
      "nestjs-postgres": 9,
      "remix-supabase": 7,
      "nextjs-prisma": 7,
      "python-fastapi": 6,
      "django-postgres": 5,
      "nextjs-supabase": 4,
      "nextjs-shopify": 5,
      "laravel-vue": 3,
      "nextjs-ai": 4,
      "react-native-expo": 3,
      "flutter-firebase": 3,
      "astro-netlify": 5,
    },
    dx: {
      "nextjs-supabase": 9,
      "nextjs-prisma": 9,
      "remix-supabase": 8,
      "astro-netlify": 8,
      "laravel-vue": 7,
      "python-fastapi": 7,
      "react-native-expo": 7,
      "flutter-firebase": 6,
      "nestjs-postgres": 6,
      "nextjs-ai": 6,
      "nextjs-shopify": 5,
      "django-postgres": 5,
      "go-grpc": 4,
      "spring-boot-k8s": 3,
    },
    cost: {
      "astro-netlify": 10,
      "nextjs-supabase": 9,
      "remix-supabase": 9,
      "react-native-expo": 8,
      "flutter-firebase": 7,
      "laravel-vue": 7,
      "nextjs-prisma": 6,
      "python-fastapi": 5,
      "django-postgres": 5,
      "nextjs-shopify": 3,
      "nestjs-postgres": 3,
      "nextjs-ai": 2,
      "go-grpc": 4,
      "spring-boot-k8s": 1,
    },
    enterprise: {
      "spring-boot-k8s": 10,
      "nestjs-postgres": 9,
      "go-grpc": 7,
      "django-postgres": 7,
      "nextjs-prisma": 6,
      "python-fastapi": 5,
      "nextjs-shopify": 5,
      "laravel-vue": 4,
      "nextjs-supabase": 3,
      "nextjs-ai": 3,
      "remix-supabase": 3,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "astro-netlify": 1,
    },
    "ai-ml": {
      "nextjs-ai": 10,
      "python-fastapi": 9,
      "django-postgres": 6,
      "nextjs-prisma": 5,
      "nextjs-supabase": 4,
      "nestjs-postgres": 3,
      "go-grpc": 3,
      "spring-boot-k8s": 3,
      "laravel-vue": 1,
      "react-native-expo": 2,
      "flutter-firebase": 2,
      "nextjs-shopify": 1,
      "remix-supabase": 2,
      "astro-netlify": 0,
    },
  },
};

// Question weights (project type matters most)
const questionWeights: Record<string, number> = {
  project: 3.0,
  scale: 1.5,
  experience: 2.5,
  timeline: 1.0,
  priority: 2.0,
};

export type RecommendationResult = {
  primary: TechStack;
  alternatives: TechStack[];
  scores: { stack: TechStack; score: number }[];
  answers: Answers;
};

export function getRecommendations(answers: Answers): RecommendationResult {
  const stackScores: Record<string, number> = {};

  // Initialize all stack scores
  for (const stack of stacks) {
    stackScores[stack.id] = 0;
  }

  // Calculate weighted scores
  for (const [questionId, answer] of Object.entries(answers)) {
    const weight = questionWeights[questionId] ?? 1;
    const questionScores = scoringMatrix[questionId]?.[answer];
    if (!questionScores) continue;

    for (const [stackId, score] of Object.entries(questionScores)) {
      stackScores[stackId] = (stackScores[stackId] ?? 0) + score * weight;
    }
  }

  // Sort stacks by score
  const sorted = Object.entries(stackScores)
    .sort(([, a], [, b]) => b - a)
    .map(([id, score]) => ({
      stack: stacks.find((s) => s.id === id)!,
      score,
    }))
    .filter((item) => item.stack !== undefined);

  return {
    primary: sorted[0].stack,
    alternatives: sorted.slice(1, 3).map((s) => s.stack),
    scores: sorted,
    answers,
  };
}

export function answersToParams(answers: Answers): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(answers)) {
    params.set(key, value);
  }
  return params.toString();
}

export function paramsToAnswers(
  searchParams: Record<string, string | string[] | undefined>
): Answers | null {
  const required = ["project", "scale", "experience", "timeline", "priority"];
  const answers: Record<string, string> = {};

  for (const key of required) {
    const value = searchParams[key];
    if (typeof value !== "string" || !value) return null;
    answers[key] = value;
  }

  return answers as Answers;
}
